// quotes array
var quotes = [
  "You can only win the game when you understand that it is a game.",
  "Hate will keep you alive where love fails.",
  "Tell me, tutor. Is revenge a science, or an art?",
  "A man who\'s got no fear is missing a friend.",
  "War is a thing of beauty, as I\'ve said before, and those who say otherwise are losing.",
  "Send not to ask for whom the bell tolls . . .",
  "It tasted sour, but that seemed right somehow.",
  "Every instinct telling me to run. Every instinct, except for that one to hold or break, but never bend.",
  "Everyone has doubts. Even Jesu had his moment, and I ain\'t him.",
  "The man looked at me as if I were mad. Maybe I was, but I\'d found my peace.",
  "And we went out into the day, and all the heat of it couldn\'t touch the ice in me.",
  "Knife-work is a dirty business, yet Brother Grumlow is always clean.",
  "The peasants will probably burn him alive, and he\'ll count it the easy way out. I kept it conversational. I find it\'s the coldest threats that reach the deepest.",
  "I kept my voice calm. It wasn\'t hard. I was calm. Anger carries less horror with it, men understand anger. It promises resolution; maybe bloody resolution, but swift.",
  "I just avenge myself better than most. Consider it a gift.",
  "Churchmen, eh? Love one minute, forgiveness the next, and then it\'s eternity on fire.",
  "In the end it seems we\'re just toys, easy to break and hard to mend.",
  "Lundist held that a man who can observe is a man apart. Such a man can see opportunities where others see only the obstacles on the surface of each situation.",
  "The best plan I\'ll come up with is the one that happens when I act.",
  "I didn\'t feel easy under the Nuban\'s scrutiny.",
  "Are you dangerous? Show me.",
  "The Nuban moved fast, but it wasn\'t his speed that impressed, it was his lack of hesitation.",
  "We all of us pass through that door, but we tend to exit of our own volition, and by degrees, sniffing the air, torn and tentative.",
  "Anything that you cannot sacrifice pins you. Makes you predictable, makes you weak.",
  "Dreams tell a man who he is.",
  "The perfumes of lords and ladies tickled at my nose: lavender and orange oil. On the road, shit has the decency to stink.",
  "I decided I liked the man. That surprised me. I\'m not given to liking people as a rule. I blamed it on my mood. Nothing like a night of whoring to turn a man soft.",
  "I could never read the Nuban. One moment he\'d seem as simple as Maical, the next, deeper than a deep well. Sometimes both at once.",
  "Free will has to be taken.",
  "The stink of death comes in many flavours, but I like to think I recognize the Reaper in all his guises.",
  "Whoever made the Nuban must have fashioned him from bedrock. I never knew a man more solid. He held his words close. Few among the brothers sought his counsel, men upon the road have little use for conscience, and although he never judged, the Nuban carried judgement with him.",
  "When in doubt, let your hate lead you. Normally I\'d reject that advice. It makes a man predictable. But there, in that miserable hall of bones, I was past caring. Hate was all I had to keep me warm.",
  "Death makes lepers of even the most popular men.",
  "Since I\'d been offered a second free blow, I took two.",
  "As with so many things in life, the bringing of death is simply a matter of timing.",
  "There is no evil, Makin. There\'s the love of things, power, comfort, sex, and there\'s what men are willing to do to satisfy those lusts.",
  "There\'s a saying on the road, \"Never trust a lettered man.\"",
  "They say fear lends a man wings. ",
  "There are few things more satisfying than taking out your frustrations upon the bearer of bad tidings.",
  "Memories are dangerous things. You turn them over and over, until you know every touch and corner, but still you\'ll find an edge to cut you.",
  "I think you need to have lived more to truly know a man\'s heart. You need to have made more transactions in life to know the worth of the coin you spend so freely.",
  "The Nuban shrugged. He never argued for the sake of being right. I liked that in him. ",
  "I thought about vengeance. About how it wouldn\'t give me back what had been taken. About how I didn\'t care. Hold to a thing long enough, a secret, a desire, maybe a lie, and it will shape you. The need lay in me, it could not be set aside.",
  "I\'d rather climb a mountain than come down one. The down-slope puts a different kind of hurting in your legs, and the gradient pulls on you every step, as if it\'s steering you, as if it\'s calling the shots. Going up you\'re fighting the mountain.",
  "Everything is for sale at the right price. A king\'s favour, a succession, even a father\'s respect.",
  "It\'s hard to carry a weight of news with none to tell and days ahead before you can release it. Good news weighs just as heavy as bad.",
  "The biggest lies we save for ourselves.",
  "We play a game in which we are gods, in which we make choices, and the current follows in our wake. We pretend a separation from the wild. Pretend that a man\'s control runs deep, that civilization is more than a veneer, that reason will be our companion in dark places.",
  "He knew better than to offer weakness to the viper. Nothing decides a man\'s mind better than opportunity.",
  "I like mountains, always have done. Big obstinate bits of rock sticking up where they\'re not wanted and getting in folk\'s way. Great. Climbing them is a different matter altogether though. I hate that. ",
  "A broadsword isn\'t the weapon to batter out submissions. It\'s for killing, pure and simple.",
  "You gamble everything on each throw, no bet hedged, no reserve. That\'s a strategy that always ends in defeat.",
  "I threw everything I had against him. All my pride, my anger, an ocean of it, the rage, the hurt. I reached back across the years. I counted my dead. I reached into the briar and touched the bloodless child who hung there. I took it all, and made a hammer of it.",
  "You\'d think there was never a good time to get kicked by a horse.",
  "The Nuban told me his people made ink by grinding up secrets. Here I am untangling them, and it\'s been a slow business.",
  "I was like Gog\'s little wooden soldier, running in wild and meaningless circles.",
  "Blood is on these hands, these ink-stained hands, but I don\'t feel the sin.",
  "I don\'t like to get angry. It makes me angry.",
  "Let a man play chess, and tell him that every pawn is his friend. Let him think both bishops holy. Let him remember happy days in the shadows of his castles. Let him love his queen. Watch him lose them all.",
  "The future is a dark place. We all die there.",
  "Even Eden has a snake problem.",
  "Hate will keep you alive where love fails.",
  "Some things can\'t be cut in half. You can\'t half-love someone. You can\'t half-betray, or half-lie.",
  "It\'s the silence that scares me. It\'s the blank page on which I can write my own fears.",
  "The dead one tried to show me hell, but it was a pale imitation of the horror I can paint on the darkness in a quiet moment.",
  "Assassination is just murder with a touch more precision.",
  "\"Water! Water!\" It\'s always water with the dying. Strange, it\'s killing that gives me a thirst.",
  "Few things worth having can be got easily.",
  "You soon learn there\'s no elegance or dignity in death if you spend time in the castle kitchens. You learn how ugly it is, and how good it tastes.",
  "Shades of grey. A man can drown in shades of grey.",
  "It\'s good to know that you don\'t know everything about a man. Good that there might always be more to come.",
  "Kent don\'t look like much but he\'s solid, all muscle and bone, quick as you like too. What makes him though, what sets him apart, is a killer\'s mind. Chaos, threat, bloody murder, none of that fazes him. Every moment of a crisis he\'ll be considering the angles, tracking weapons, looking for the opening, taking it.",
  "There is something brittle in me that will break before it bends.",
  "Perhaps if the Prince of Arrow had brought a smaller army I might have had the sense to run. But he overdid it.",
  "The bladder-pipe, a local Highlands speciality, is to music what warthogs are to mathematics. Largely unconnected.",
  "\"It cannot be helped.\" Gorgoth\'s hands closed into massive fists. \"It\'s in his dena.\"",
  "I remembered how Gog had fought to save his little brother. How pure that fury had been. I missed that purity in myself.",
  "Only yesterday every choice came easy. Black or white. Stab Gemt in the neck or don\'t. And now?",
  "Shades of grey. A man can drown in shades of grey.",
  "His dena. The story of every man, written at his core, what he is, what he will be, written in a coil in the core of us all.",
  "I\'d never heard the monster say so many words in a row. \"I\'ve opened up a lot of men, Gorgoth, and if anything is written there then it\'s written red on red and smells bad.\"",
  "\"The centre of a man isn\'t found by your geometry, Highness.\" He held me with those cat\'s eyes. He\'d never call me Highness before either. Probably the closest to begging he would ever come.",
  "Play your pieces. Win the game. Take the hardest line.",
  "At least Gog will like it there. Everything burns.",
  "Kent went to his knees in an instant, as pious a killer as I ever knew. Makin followed with unseemly haste for a man who\'d sacked a cathedral in his time.",
  "There\'s not many that will take my hand since the necromancy took root in me.",
  "You\'ve got to hunt your fears, Gog. Beat them. They\'re your only true enemies.",
  "I\'m not given to should haves. But I should have.",
  "I wanted to win. The throne was just the token to demonstrate that victory. And I wanted to win because other men had said that I may not.",
  "It sometimes seems I stand three steps outside the lives of other men.",
  "Giving in to things becomes a habit.",
  "I don\'t have an angel on one shoulder and a devil on the other. I got me a devil on both.",
  "We\'re brittle things, us men.",
  "A blow to the skull can knock a deal of sense out of a man.",
  "Memory is all we are. Moments and feelings, captured in amber, strung on filaments of reason. Take a man\'s memories and you take all of him. Chip away a memory at a time and you destroy him as surely as if you hammered nail after nail through his skull.",
  "If you\'re determined, if you set your mind, there are never enough hands to pull you back.",
  "When a game cannot be won, change the game.",
  "Find your relief where you will. Move on each day and leave the shit, all manner of shit, behind you.",
  "With enough hurt we all sound the same.",
  "Weakness is a contagion, one breath of it can corrupt a man whole and entire. Now though, even with all sound the same.",
  "Mountains are a great leveller. They don\'t care who you are or how many.",
  "The mountains told me I couldn\'t.",
  "Mountains have no memory, no judgments to offer. There\'s a purity in the struggle to reach a peak.",
  "You leave your world behind and take only what you need. For a creature like me there is nothing closer to redemption.",
  "They say don\'t look down, but I like to. I like to see the loose pieces fall away and become lost in the distance.",
  "When I climb, and only then, on the very edge of everything, I catch stray notes. Like words robbed of meaning on the cusp of hearing…the music almost reaches me. And for that I would dare any height.",
  "There are no half measures in such ascents: you place everything you are or will be on each decision. Lives can be lived in this manner, but I do not recommend it.",
  "The art of survival in the mountains is knowing when to give up. The art of reaching the top is knowing when not to.",
  "When you\'re climbing you take nothing with you that you do not absolutely need. That\'s a good discipline to acquire, and the mountains teach it to you for free.",
  "They say that time is a great teacher but unfortunately it kills all its pupils. The mountains are also great teachers, and better still, they let the occasional star pupil live.",
  "It isn\'t the danger or the challenge that keeps me climbing, it\'s the purity and focus.",
  "I heard the expression a few more times in the years that followed, generally when somebody was off on mysterious business. Taking a rock for a walk.",
  "Makin once told me that a man who\'s got no fear is missing a friend.",
  "And a man should be a little scared of himself surely? Of what he might do. To know thyself must be terribly dull.",
  "\"Do you like dogs, Maical?\" I asked him. \"Beef\'s better,\" he said, \"or mutton.\"",
  "A fresh challenge is often the way to keep from brooding on the past.",
  "I found the long silences a trial. My mind wandered along dark paths.",
  "When ambition gets its teeth into you it\'s hard to know how to just enjoy what\'s in front of you.",
  "Third time\'s the charm, but there\'s no point tempting the fates—unless you\'ve got a big enough sword to kill them too.",
  "We die a little every day and by degrees we\'re reborn into different men, older men in the same clothbes, with the same scars.",
  "Always ready for trouble was Red Kent, though he never sought it out.",
  "God may mould the clay and fashion some of us hale, some strong, some beautiful, inside we make ourselves, from foolish things, breakable, fragile things: the thorns, that dog, the hope that Katherine might make me better than I am. All of us fractured, awkward collages of experience wrapped tight to present a defensible face to the world. And what makes us human is that sometimes we snap. And in that moment of release we\'re closer to gods than we know. ",
  "When men look too long into the fire it looks back into them. It burns out what makes them men.",
  "Man is doomed to repeat his mistakes time and again because he learns only from experience.",
  "Fire isn\'t patient. Fire does not negotiate. I should have known these things.",
  "It\'s easy to lose faith on the mountain, but also to find it. Somehow being a few thousand feet closer to God makes all the difference.",
  "Trust is a fine thing but try not to build plans upon it.",
  "I think of a snow-globe broken long ago and wonder how all this will settle.",
  "Sometimes a hurt is too big and we skirt around the edge of it, looking for our way in.",
  "The world isn\'t shaped by reasonable men. The world is a thief, a cheat, a murderer.",
  "\"There\'s evil in you, Jorg,\" she says. \"Perhaps,\" I say. \"There\'s evil in a lot of men. Women too. Maybe I just wear it more plainly.\"",
  "I could blame them for my excesses, but something tells me that my failings are my own.",
  "There\'s something about a fight that makes you forget your troubles.",
  "Mainly it\'s that all your troubles are suddenly very small in the face of the new problems swinging your way with sharp edges on them. ",
  "I\'ve become good at finding crumbs of comfort. Sometimes they\'re all you have to eat.",
  "Makin looked to have retreated into that closed and lonely place that we all reach if we keep digging. Dig a little deeper than that and you\'re in hell all of a sudden.",
  "I wondered if I was dying piece by piece, a slow introduction rather than the traditional unexpected embrace.",
  "Wanting is free. Want makes fools of men.",
  "I\'ve broken something precious and I\'m carrying the pieces, knowing they can\'t be reassembled.",
  "There are men to walk to the mountain with and then there are men that are the mountain.",
  "Gorgoth, though I may not call him brother, was forged from the qualities I lack.",
  "Even the smallest fish can choke you.",
  "Winners may be admired but that are not liked.",
  "When pain bites, men bargain. Boys too. We twist and turn, we plead and beg, we offer our tormentor what he wants so that the hurting will stop. And when there is no torturer to placate, no hooded man with hot irons and tongs, just a burn you can\'t escape, we bargain with God, or ourselves, depending on the size of our egos",
  "We all become weasels with enough hurt on us.",
  "If you don\'t know where to look for something, just start looking where you are.",
  "A man\'s scars tell his story. Yours is a story I like to read.",
  "You discover that everything tastes good when your stomach is empty. If you look at a mouldy piece of cheese and your mouth doesn\'t water—you\'re just not proper hungry.",
  "Being dead doesn\'t make you right. Everybody dies.",
  "For all that he was a dark and deadly bastard, Kent had himself a pious nature, the good kind of pious, or at least the better kind.",
  "Let people pray to God, it\'s nothing to me. Some good may even come of it, if goodness is something that matters to you. Trap him in churches if you must, and lament him there. But Roma? Roma is a weapon used against us. A poison flavoured sweet and given to hungry men.",
  "We\'re built of contradictions, all of us. It\'s those opposing forces that give us strength, like an arch, each block pressing the next. Give me a man whose parts are all aligned in agreement and I\'ll show you madness. We walk a narrow path, insanity to each side. A man without contradictions to balance him will soon veer off.",
  "Makin walked away because his contradictions allowed him a compromise. Mine are not so gentle.",
  "Red slaughter was an option, my fingers itched for a sword hilt and I felt fairly sure I could kill everyone on the stage without breaking sweat.",
  "Instead I tried reason, or at least my brand of reason. ",
  "I am King Jorg of Renar. I have killed more priests than you have killed witches, and I say you will release these three for no reason other than it pleases me.",
  "It\'s strange how quickly impersonal lust can slip into revulsion. It probably crosses the tail end of that thin line the poets say divides love and hate.",
  "In any case, you don\'t want to believe everything you read, and the older a book is the less reliable its stories.",
  "Revenge doesn\'t need explanation.",
  "An angry enemy is the best kind to have.",
  "Embrace what you fear, I had told Gog. Hunt your fears. And what is death if not the ultimate of fears, the final enemy?",
  "Men are afraid of dying. Not of death. Men want it to be quick, clean. That\'s the worst thing, the wound that lets you linger.",
  "When a name is held secret its power multiplies. The Nuban toppled without hesitation and I felt that he would never rise again. As he fell my anger rose.",
  "Battle makes more corpses, not more men.",
  "Anger always opens a new reserve, a little something you\'d forgotten about.",
  "So much in life is simply a matter of timing.",
  "We just needed a few more minutes, but sometimes you don\'t get what you want, or what you need.",
  "In the past I have been saved by a horse. Not borne to safety by a noble steed, but saved by the wild kick of a panicked horse. That had been unexpected. It probably surprised Corion even more. To be saved by a sheep\'s weak bladder though…that takes the biscuit. It takes all the biscuits.",
  "\"Shitdarn!\" I\'d learned that one from Brother Elban and felt a duty to roll it out from time to time since no one else ever used it.",
  "There are no simple answers in the world, Jorg. Every question has sides. Too many of them. Everything is knotted. But you make the questions simple and somehow it works. For other men the world is not like that. ",
  "I have regrets... We\'re built of those.",
  "In the long ago, in the gentle days, Brother Grumlow carved wood, worked with saw and chisel. When hard times come carpenters are apt to get nailed to crosses. Grumlow took up the knife and learned to carve men. He looks soft, my brother of the blade, slight in build, light in colour, weak chin, sad eyes, all of him drooping like the moustache that hangs off his lip. Yet he has fast hands and no fear of a sharp edge. Come against him with just a dagger for company and he will cut you a new opinion.",
  "Sometimes I feel the need of an avalanche within me. A clean page with the past swept away. Tabula rasa.",
  "A man is made of memories. It is all we are. Captured moments, the smell of a place, scenes played out time and again on a small stage. We are memories, strung on storylines—the tales we tell ourselves about ourselves, falling through our lives into tomorrow.",
  "I first thought to pay for affection. I know better now. Affection is always paid for.",
  "A man with his head bowed is hiding his face and worthy of close inspection.",
  "For a small box it surely held a weight of memory. Perhaps more than I could carry.",
  "He carried doubt with him, doubt of self, doubt of motives, the kind of uncertainty that eats at a man like cancer.",
  "Men will die for many things; lives hoarded with care can be spent for the strangest of reasons.",
  "All men will dig their heels in if pushed enough.",
  "All men will reach the point that they say \"no\" for no reason other than opposition, for no reason other than the word fits their mouth, and tastes as good as it sounds. ",
  "Revenge is far less sweet than it promises to be. An empty meal, however long you take over it.",
  "If she had any sense she would run. If I had any decency I would make her.",
  "All young men are a little in love with death.",
  "Beware of ghosts bearing gifts, they say.",
  "Whatever you look into can look back into you.",
  "We aren\'t meant to live forever, nor dwell in solitude. A life without change is no life.",
  "The metal weighed heavy over my heart. Perhaps guilt feels like that.",
  "Gelleth taught me a lot of things. That we\'re children in a world we don\'t own or understand. That we stand alone and whether I fail or succeed depends on the strength of my will. On how far I will go. And that no one will come to help us in our hour of need. And that some things can\'t be fixed even if you bring the sun to earth and crumble mountains.",
  "Revenge can be the easy path to follow though I have often painted it as the hardest.",
  "You won\'t see Brother Grumlow try to knife you, only the sorrow in his eyes as you fall.",
  "What man can hope for victory when his doom watches from every shadow?",
  "To get somewhere in life you have to walk over bodies, and I\'d paved my way with corpses and more corpses. Gelleth burned for my ambition. It still does.",
  "A goblet, the box, a knife. Drink to forget, open to remember, or slice to end.",
  "To fight so hard and not even come close to victory. That had a bitter taste.",
  "The most subtle tools have the most profound effect.",
  "Sometimes it\'s easier to love someone with flaws you can forgive in return for them forgiving yours.",
  "There\'s no victory without sacrifice.",
  "You have to raise the stakes and raise them again.",
  "We are made of flesh before we are made of dreams, and flesh cares about pain.",
  "I would give you something for the pain, Brother Kent, but I want you to make a battle of it. Fight these burns. Win. I\'m offering no terms for surrender.",
  "The secret is to know that there is only one game and the only rules are your own.",
  "Red would be good, Kent. But I fear I am darker than that.",
  "Death and fire had their hooks in me. Deeper than deep. And each had started to pull.",
  "I had that old thirst on me once again. Blood would flow.",
  "This is not your game! I don\'t play by the rules you choose.",
  "The devil makes work for idle hands.",
  "Whatever may be said about the aftertaste, in the moment revenge tastes sweeter than blood, my brothers.",
  "I laughed. The joy of it, the roaring joy of destruction. That\'s why the flames dance. For joy. ",
  "There\'s only one fire.",
  "In the end, my brothers, there is no price I will not pay to win this game of ours. No sacrifice too great that it will not be paid to stop another placing their will over mine. ",
  "I climbed God\'s finger to stand alone in that high place and find a new perspective. ",
  "I went to the mountain for Gog, even though I couldn\'t save him from his fire, just as no one can save me from mine.",
  "I fought the all-sword, Master Shimon with the sword-song all around, and we made a thing of beauty.",
  "\"Christ-on-a-bike!\" One of Makin\'s oaths, that. I don\'t know what a bike is but it sounds painful.",
  "The best part of me still hangs there, on those thorns.",
  "There are hard paths and there are the hardest paths.",
  "Sin doesn\'t stick to a child\'s skin the way it clings to a man\'s.",
  "Sir Kent had got himself a bad case of religion.",
  "Often it\'s not in me to take the sensible path.",
  "Don\'t live by half measures.",
  "But words are only words and they seldom turn a person from their path unless they want to be turned.",
  "Any closed box, any secret, will gnaw at you.",
  "Nothing can be cut away without loss.",
  "There are truths you know but will not speak.",
  "You couldn\'t leave a gap long enough that it would force the Nuban to fill it.",
  "Whatever the road to hell is paved with, the key is to take one step at a time.",
  "All you need to decide is whether to feed the fire or be the fuel.",
  "The best part of me still hangs there, on those thorns.",
  "There are hard paths and there are the hardest paths.",
  "Too much soft living and peace can choke a man sure as any rope.",
  "But I didn\'t love her, not the irrational foolish love that can overwhelm a man, wash him away and strand him on unknown shores.",
  "Sin doesn\'t stick to a child\'s skin the way it clings to a man\'s.\"",
  "Perhaps he just needed something to worry about again, so he could stop worrying.",
  "Scale changes everything.",
  "Sir Kent had got himself a bad case of religion.",
  "There are more things in heaven and earth, Makin, than are dreamt of in your philosophy.",
  "I told myself that I chose to face what I feared.",
  "I know you\'re right, but often it\'s not in me to take the sensible path.",
  "I maintain a balanced view of the world, but that balance is always in my favour.",
  "Perhaps I just wanted to know what it was that I wanted. Maybe that is all that growing up means.",
  "Often the lack of a question will prompt an answer, sometimes an answer to a question you might not have.",
  "We can\'t be trapped by fear. Lives lived within such walls are just slower deaths.",
  "I feared to do it and though commonsense may occasionally bind me, I\'ll be fucked if fear will.",
  "Don\'t live by half measures. No half measures. Some things can\'t be cut in half. You can\'t half-love someone. You can\'t half-betray, or half-lie.",
  "Some places a man needs to have his own two legs take him. Some journeys need a different perspective. The miles mean more if you have travelled them one step at a time and felt the ground change beneath your feet.",
  "I had only one man who I couldn\'t order, who at the very last would twist my head off rather than obey against his instinct. Everyone needs somebody like that around sometimes. ",
  "Any closed box, any secret, will gnaw at you, day on day, year on year, until it reaches the bone. ",
  "Nothing can be cut away without loss. Even the worst of our memories is part of the foundation that keeps us in the world.",
  "Sometimes the only option is to raise the stakes, to throw yourself the other way, to force your opponent further down the path they\'ve chosen, further than they might want to go.",
  "There are truths you know but will not speak. Even to yourself in the darkness where we are all of us alone.",
  "Honesty remained my sharpest weapon.",
  "You couldn\'t leave a gap long enough that it would force the Nuban to fill it.",
  "Too much cleverness can be a torment to a man, setting his wits against his faith.",
  "I wanted to earn the edge that the Nuban showed in my father\'s dungeons, to be forged in battle. And I would find those things in the hard times. I would steer my brothers into the crucible where the Hundred wet their swords, and see what would unfold.",
  "Dirt can get inside you, too deep to be scrubbed out, too deep to be bled out, perhaps too deep even to be burned out.",
  "We\'re meat and dirt. Nobody is clean and nothing can wash away our stain, not the blood of the innocent, not the blood of the lamb.",
  "It might be easier to fall into such enchantments from a nightmare than from honest sleeping.",
  "It\'s good that you have some doubt in you, Gomsty. Men who are certain of everything—well, perhaps they\'re not men at all.",
  "And how did I get my box of gold? By setting my will behind a sharp edge and applying an unhealthy amount of determination.",
  "I don\'t doubt that for every step you take toward Roma, God sounds three steps further away.",
  "Life can be complicated enough even when nobody is trying to kill you.",
  "We rode in silence for a while and I wondered if men were the world\'s leaves. If as we aged the world filled us with its poisons so as old men, filled to the brim with the bitterest gall, we could fall into hell and take it all with us. Perhaps without death the world would choke on its own evils.",
  "There\'s a road to hell that is paved with good intentions but it\'s a long route. The quicker path is paved with the kind of ignorance that clever men who just don\'t want to know are best at.",
  "Holding a sword always leaves you with a little slice of hope.",
  "At the sharp end of things there is only room for ourselves.",
  "The Bad Dogs died, parted from heads, from limbs, without time for one man to fall before the point of my sword ploughed a red furrow through the next. Not before or since have I taken such unadulterated joy in slaughter.",
  "Whatever the road to hell is paved with, the key is to take one step at a time.",
  "All you need to decide is whether to feed the fire or be the fuel.",
  "\"That\" is never all there is to it. Hurt spreads and grows and reaches out to break what\'s good. Time heals all wounds, but often it\'s only by the application of the grave, and while we live some hurts live with us, burning, making us twist and turn to escape them. And as we twist, we turn into other men.",
  "Well, you can lead a horse to water, but I choose what I damn well drink and I hold a low opinion of prophecy.",
  "Fear and ambition, a good combination.",
  "Being at the sharp end of the stick changes your view on the business of poking.",
  "Words are blunt instruments, better suited to murder than to making sense of the world.",
  "We walk a knife-edge each day though, and most don\'t know it.",
  "I reached shoulder-deep into my well of obscenities and released a string of quite spectacular examples. It deserved a better audience.",
  "When you\'re in a dark place, and your light is going to run out before too long, you get on with things. It\'s a wonder to me how few people apply that same logic to their lives.",
  "I saw nothing but puzzles and sorrow.",
  "The Greeks loved paradoxes. Maybe they used them as currency.",
  "That\'s what happens when you stop. Take a rest and the world catches up with you. Lesson in life—keep moving.",
  "\"A man without fear is missing a friend.\" An old ghost once told me that.",
  "So much of the world is about surfaces, the eye deceived, with the truth in the unknown and unknowable depths beneath.",
  "There was a time when I was pleased to find that something still scared me. Pleasure turning to dismay. It seems men have far more to fear than boys. Pleasure turning to dismay. It seems men have far more to fear than boys.",
  "Surfaces and reflections, Makin, worlds divided by such thin barriers, unseen, unknowably deep.",
  "We all carry the seeds of our own destruction with us, we all drag our history behind us like rusted chain.",
  "And in the end the body\'s wants prove stronger than the mind\'s.",
  "I spoke to my demons, addressing each with long and dreary monologues as I twisted in the dust.",
  "It struck me that finding someone I might call a friend had been a rare thing in my life.",
  "A man who can\'t make sacrifices has lost before he starts.",
  "It doesn\'t take many hands or much imagination to build a reputation on blood and horror.",
  "Dear lady, I killed them from youngest child to oldest woman, and when I was done I blunted three axes dismembering their corpses. I am Jorg of Ancrath—I burned ten thousand in Gelleth and didn\'t think it too many.",
  "Never refuse water in dry places—and there is no place more dry than the seas off Afrique.",
  "However bright a paradise I may have found, the past would catch me up, rise around me in a dark tide, and devour peace.",
  "If you must run, have something to run toward, so it feels less like cowardice.",
  "Getting everything you wish for is nearly as dire a curse as having all your dreams come true.",
  "The balance between the force that may be exerted in such endeavours and the nature of the response when offence is taken varies with geography.",
  "Never refuse a drink in a dry place.",
  "I\'d never heard thanks offered with less gratitude.",
  "I\'m not used to pretending to like people. And I speak six languages. I didn\'t mention that none of those were Moorish, but I find hand gestures and a sharp edge go a long way toward cutting through misunderstanding.",
  "Clarity of vision is a thing much prized. I find when you turn that clear sight upon yourself—and see through to the truth behind your own actions—it might be better to be blind.",
  "That weakness that infects all men, that is part of how we are made, had found a way into me.",
  "We had us a murderous little struggle: civil wars are always brutal, old wounds left too long festering get to spill out their poison over new generations.",
  "I failed to see how I could be more serious, but some men take time to adjust to unfamiliar circumstances. ChooOOOooom.",
  "Choosing the right position had kept Kent alive more times than any armour or skill with a blade.",
  "To some men there\'s no poison worse than a gift, none worse than a measure of pity. I would know.",
  "Katherine looked up with murder in her eyes. I like people who have the grace to show their anger.",
  "An unease rose in me. Each mile took us further into a prison. The desert trapped us better than high walls.",
  "Beware the camel\'s nose.",
  "It\'s an unsettling business having to re-evaluate your world view.",
  "It\'s our actions that define us, not the manner in which we reach the decision to act.",
  "It\'s an irony of our times that men seeking peace must make war.",
  "He had the grace or commonsense not to smirk at my apocalyptic turn of phrase.",
  "All men need hope. Even men of numbers.",
  "My sword stood between us now. I had no recollection of drawing it. The rage I needed flared and died, flared again.",
  "The magic lies in the first number, the mathematics in the second.",
  "The need for vengeance, for retribution against Qalasadi after his attempt on my family, had never burned so bright as the imperative that took me to Uncle Renar\'s door. In fact it felt good to let it drop. Lundist and the Nuban would have been proud of me, but in truth I liked the man and it was that rather than any new-found strength of character that allowed me to set it aside.",
  "When a man doesn\'t bother to keep secrets from you, you know that you\'re in trouble.",
  "Theft is about timing and timing can be calculated.",
  "The desert is place where a man can be heard and where a man can listen.",
  "A wise man told me that history will not stop us repeating our mistakes, but will at least make us ashamed of doing so.",
  "Whatever poetry such things hold I am deaf to it.",
  "It says here that a prediction will diverge from the truth. The further the prediction is carried, the larger the discrepancy.",
  "A trouble named is a trouble tamed.",
  "There are no happy endings for such as us, Chella. No redemption. Not with our sins. Any joy is borrowed—laughter shared on the road, and left behind.",
  "We have both walked black paths, lady. Don\'t think that mine leads back into the light. Of all those that tried to guide me, of my father, of the whispers from the thorn bush, of Corion\'s evil council, the darkest voice was ever mine.",
  "My past lay black, the future burned, and in the thin slice between, the world expected me to be a father, to hold a son, to save him, save them all?",
  "The Nuban never held grudges—said he had enough to carry and a long way to go.",
  "Heaven, hell, and earth, three that are one—there can be no change above or below that isn\'t mirrored here. This world, where our lives are spent, is both a lock and a lever.",
  "All these narrow paths. A man can reach into anything and turn it to his cause. It\'s not want, or desire, just certainty. Only be assured that whatever you reach into will reach into you in turn.",
  "There are times when we realize we\'re just passengers, all our intellect and pontification, carried in meat and bones that knows what it wants.",
  "When flesh meets fire it wants to pull back and does so whatever you might have to say about it. There can be times, when man meets woman, that the same forces work in reverse.",
  "It might be said that destruction and disaster have always dogged my heels, but never before had that curse been so manifest.",
  "I may be foolish on occasion, but I\'m not an idiot.",
  "Watchful men are to be watched.",
  "Any kind of faith stacked up behind a creed or title could amplify the will of the relevant figurehead to a frightening degree.",
  "In some inner darkness cold winds stirred and the ember of an old rage glowed once more.",
  "I tilted my head, seeing the pale-eyed killer beside me without looking. Road-eyes, that\'s called. Seeing without looking. I drew the deepest breath and that hidden ember grew white-hot.",
  "Don\'t waste your speed at the start of the first move. All that does is advertise that it is a move.",
  "Rumours are fine. Rumours just put an edge on things—add some weight to what I have to say. Accusations... not so good. Charges? Then it\'s time to march on Roma.",
  "If God talks to anyone, Kent, it\'s not that evil old woman back there. That faith you\'ve found—you didn\'t find it in church, now did you? You found it in pain and blood. Whatever reached out to touch you, it wasn\'t a priest in robes.",
  "\"The holy spirit found me, Jorg. Christ Jesu, risen, led me out of darkness and cooled my burns.\" No \"king\" today, no \"sire.\"",
  "I don\'t respect many men and Kent was never sharp enough of wit, never wise enough, never virtuous enough to inspire me. But I respected his instincts as a killer and I liked the honesty of the man.",
  "And who was I to judge? I\'d fucked a necromancer and killed a Pope within the space of a week.",
  "\"I need to trust you, Kent. I need some of that faith. So listen to that spirit. Listen hard. And if I need to die for my crimes—be the one to strike me down.\" The cold wind blew between us. And I discovered I meant every word. I dared him, as I dared the storm long ago.",
  "Quality costs. Manners cost nothing.",
  "The future is a dark place. We all die there.",
  "I betrayed him and left him to die alone. And though there was no price I\'d not pay to undo that wrong, even an emperor hadn\'t the coin to set it right.",
  "Time has its own way with us. We burn in time\'s fire.",
  "To see in the dark you need to be dark.",
  "When a faction is broken it\'s often the case that the pieces may be swept up easily.",
  "A bit of wisdom from the road. Kill the head and the body is yours.",
  "There\'s a slope down toward evil, a gentle gradient that can be ignored at each step, unfelt. It\'s not until you look back, see the distant heights where you once lived, that you understand your journey.",
  "Secrets are best kept behind a single pair of lips.",
  "I walked toward them. Several backed away, without knowing why—the instinct that removes the sheep from the wolf\'s path.",
  "\"He\'s trapped in here with us.\" So much in life is a matter of perspective. \"I rather think you\'re trapped in here with me.\"",
  "Seating arrangements do not make emperors, gentlemen. That\'s what we\'re here to vote upon.",
  "Men of empire. A better man than I would have won your support with the goodness of his deeds, the clarity of his vision, the truth of his words. But that better man is not here. That better man would fail before the dark tide that rushes toward us.",
  "Dark times call for dark choices. Choose me.",
  "\"Numbers never lie, my emperor.\" Taproot shook his head. \"Only men.\"",
  "I\'d called them brothers on the road many a time, stood with them in the face of danger, shared meat and mead. A brotherhood of the road, sure enough, but a mean thing, men to die with rather than for.",
  "In the end there\'s no magic. Only will.",
  "I have lived a life driven by desire, the desire for revenge, for glory, to have what is denied me, a simple directive, pure and edged like a weapon. And such desire, such concentrated wanting, is the foundation of all magic.",
  "They\'re channels where men\'s will has cut paths through what is real.",
  "I told him because there\'s a power in the telling of a truth, and because reason has a keen edge.",
  "Death isn\'t what it used to be.",
  "A single maple leaf, scarlet with the season\'s sin. A sign. In that moment I knew myself too full of poison to do anything but drop. The fall had come for me.",
  "We\'re fashioned by our sorrows—not by joy—they are the undercurrent, the refrain. Joy is fleeting.",
  "They tell me no and think there must be something I won\'t sacrifice to get what I want. What I need.",
  "It doesn\'t pay to trust a lettered man on the road, Brothers, their heads are full of other men\'s ideas.",
  "A man may fear his own shadow, but here is a pale shadow that fears the man who cast him.",
  "I could say I wept for Sunny, or for the horror of a world where such things happen, but in truth I wept for myself, in fear.",
  "There\'s a road to hell that is paved with good intentions but it\'s a long route.",
  "There is no sound more annoying than the chatter of a child, and none more sad than the silence they leave when they are gone.",
  "Memory is all we are. Moments and feelings, captured in amber, strung on filaments of reason. Take a man\'s memories and you take all of him. Chip away a memory at a time and you destroy him as surely as if you hammered nail after nail through his skull.",
  "I\'ve always seen \'no\' as a challenge rather than an answer.",
  "Makin once told me that a man who\'s got no fear is missing a friend.",
  "They shot my idiot",
  "Some men name their swords. I\'ve always found that a strange affection. If I had to call it something I would all it \"Sharp\".",
  "A fool may scrawl on a slate and if no one has the wit to wipe it clean for a thousand years, the scrawl becomes the wisdom of ages.",
  "In battle though his hands grow clever, and you\'d think him whole, until the din fades, the dying fall, and Maical wanders the fields weeping.",
  "If the sins of the flesh ever got old I didn\'t ever want enough years on me to know it.",
  "Some pain you can distance yourself from, but a headache sits right where you live.",
  "Beside me Makin looked to have retreated into that closed and lonely place that we all reach if we keep digging. Dig a little deeper than that and you\'re in hell of a sudden.",
  "When a game cannot be won, change the game.",
  "When pain bites, men bargain. Boys too. We twist and turn, we plead and beg, we offer our tormentor what he wants so that the hurting will stop. And when there is no torturer to placate, no hooded man with hot irons and tongs, just a burn you can\'t escape, we bargain with God, or ourselves, depending on the size of our egos",
  "All men will dig their heels in if pushed enough. All men will reach the point that they say \"no\" for no reason other than opposition, for no reason other than the word fits their mouth, and tastes as good as it sounds.",
  "Call it a personal foible. Some people are scared of spiders. I\'m scared of immolation. Also spiders.",
  "Man is doomed to repeat his mistakes time and again because he learns only from experience.",
  "Killing takes space. You need to move, to advance, to withdraw, and sometimes to just plain run for it.",
  "We\'re built of contradictions, all of us. It\'s those opposing forces that give us strength, like an arch, each block pressing the next.",
  "We\'re going to need a bigger army.",
  "It\'s good to be the king. Except when you get hit in the head with a sword.",
  "When you fight among subjects you are a figure, a form, an idea.",
  "Many men do not look their part. Wisdom may wait behind a foolish smile, bravery can gaze from eyes that cry fright.",
  "It seems terror is a companion in the soft years when everything is new, and returns to us with age, as we acquire things to lose.",
  "I\'ve become good at finding crumbs of comfort. Sometimes they\'re all you have to eat.",
  "We discovered the same thing, the Builders and me; if something shatters your world then afterward you find the rules have changed. They had the Day of a Thousand Suns. I had the thorns.",
  "The rain hammers down, pricked with ice, but I\'m burning with the memory of those thorns and the fever they put in my blood. No absolution in this storm-the stain of sin is past water\'s touch.",
  "Two against five are the best odds I\'ve had in a while.",
  "My name is Honorous Jorg Ancrath, my password is divine right. Now open the fecking door.",
  "You got responsibilities when you\'re a leader. You got a responsibility not to kill too many of your men. Or who\'re you going to lead?",
  "The way to break the cycle is to kill every single one of the bastards that fucked you over. Every last one of them. Kill them all. Kill their mother, kill their brothers, kill their children, kill their dog.",
  "You\'d think priests would be better liars, what with their jobs and all.",
  "I\'ll tell you now. That silence almost beat me. It\'s the silence that scares me. It\'s the blank page on which I can write my own fears. The spirits of the dead have nothing on it.",
  "I may be running out of options, but running out isn\'t an option.",
  "I think maybe we die every day. Maybe we\'re born new each dawn, a little changed, a little further on our own road. When enough days stand between you and the person you were, you\'re strangers. Maybe that\'s what growing up is. Maybe I have grown up.",
  "Some men are too dull to feel what might happen. Others torture themselves with maybes and populate their dreams with horrors more terrible than their worst enemy could inflict upon them.",
  "\"This is where it starts. When they write the legend, this will be the first page. Some old monk will go blind illuminating this page, Makin. This is where it all starts.\" I didn\'t say how short the book might be though.",
  "Each day the memories weigh a little heavier. Each day they drag you down that bit further. You wind them around you, a single thread at a time, and you weave your own shroud, you build a cocoon, and in it madness grows.",
  "You sit here with your yesterdays queuing at your shoulder. You listen to their reproach and curse those that gave you life.",
  "I\'ve been known to be contrary. When something pushes me, I shove back. Even if the one doing the pushing is me. It would have been easy to gut him then and there. Satisfying. But the need was too urgent. I felt pushed.",
  "It never pays to walk blindly. Especially not in your own castle where familiarity hides so much - even when we have the eyes to see.",
  "Makin once told me that a man who\'s got no fear is missing a friend.",
  "If the sins of the flesh ever got old I didn\'t ever want enough years on me to know it",
  "In the end though, everybody dies, but not everybody lives—the climber, though he may die young, will have lived.",
  "He made his own silent screams then and tried to die. But I held him there.",
  "The surgeons like to bleed a man, to let ill humours out, so that he may face the world anew. Perhaps they should just hand him a quill and let the poisons spill from him whilst he keeps his blood for its intended purpose.",
  "We\'re not memories, Katherine, we\'re dreams. All of us. Each part of us is a dream, a nightmare of blood and vomit and boredom and fear. And when we wake up – we die.",
  "No sense of satisfaction, but my uncle\'s death had taught me that revenge is far less sweet than it promises to be. An empty meal, however long you take over it.",
  "Sometimes I wished I could cut away old memories and let the wind take them. If a sharp knife could pare away the weakness of those days, I would slice until nothing but the hard lessons remained.",
  "This is where the wise man turns away. This is where the holy kneel and call on God. These are the last miles, my brothers. Don\'t look to me to save you. Don\'t think I will not spend you. Run if you have the wit. Pray if you have the soul. Stand your ground if courage is yours. But don\'t follow me. Follow me, and I will break your heart.",
  "I kissed her cheek then, because I feared to do it and though commonsense may occasionally bind me, I\'ll be fucked if fear will.",
  "I knew myself broken, to burn over every refusal, to feel my blood rise at the slightest provocation, but knowing and fixing are different things.",
  "Nature shaped the claw to trap, and the tooth to kill, but the thorn...the thorn\'s only purpose is to hurt.",
  "I would shake the world until its teeth rattled if that was required to have it spit out an answer.",
  "Every man has his thorns, not of him, but in him, deep as bones. The scars of the briar mark me, a calligraphy of violence, a message of blood-writ, requiring a lifetime to translate.",
  "Some tell it that \"sorry\" is the hardest word, but for me it has always been \"help\".",
  "My enemies defeated, and yet the sorrow remained, keener, more true, more clean, for I had always owned it. It echoed back to the thorns, the tone of a bell resounding through the years.",
  "People who talk about the weather would be better served by admitting they\'ve nothing to say but like the sound of their own voice.",
  "Pretty armour doesn\'t make a warrior.",
  "A victim who believes himself anticipated at every turn is not only crippled by uncertainty but also easier to predict.",
  "Men are busy dying from the moment they\'re born but it\'s a crawl from the cradle to the grave.",
  "You can\'t grow if you\'re constantly defined by this collection of frozen moments that you keep returning to. And if you can\'t grow, you\'re not alive.",
  "Decadence begins when the budget to beautify a man\'s home exceeds the coin spent to ensure its defense.",
  "To look into what will be isn\'t unlike self-abuse. To watch yourself march through possibilities, to follow the truth through all those twists and turns. Just a little might stunt your growth.",
  "Though I might walk where angels fear to tread, I try not to rush in like a fool.",
  "Tents are boasters, telling exaggerated tales of the weather they save you from.",
  "There are few problems that won\'t go away if you ignore them long enough."
];

// function to load random quote into #quote div
var loadRandomQuote = function () {
  document.getElementById('quote').innerHTML = quotes[ Math.floor ( Math.random() * quotes.length ) ];
}

// loads a random quote on page load
window.onload = loadRandomQuote();

// loads a random quote on button press into #quote div
document.getElementById('quote').onclick = function() {
  loadRandomQuote();
}
